amazon:
  service: S3
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: "US West (Oregon)" #<%= ENV['BUCKETEER_AWS_REGION'] %>
  bucket: <%= ENV['S3_BUCKET_NAME'] %>
 
local:
    service: Disk
    root: <%= Rails.root.join("storage") %>
    
test:
    service: Disk
    root: <%= Rails.root.join("tmp/storage") %>
  
  #   :storage => :s3,
#   :s3_credentials => {
#     :bucket => ENV['S3_BUCKET_NAME'],
#     :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
#     :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']